// Code generated by "stringer -type=saveStateCode ./save_protocol.go"; DO NOT EDIT.

package backend

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[awaitDescription-1]
	_ = x[awaitMeasurement-2]
	_ = x[finished-3]
}

const _saveStateCode_name = "awaitDescriptionawaitMeasurementfinished"

var _saveStateCode_index = [...]uint8{0, 16, 32, 40}

func (i saveStateCode) String() string {
	i -= 1
	if i < 0 || i >= saveStateCode(len(_saveStateCode_index)-1) {
		return "saveStateCode(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _saveStateCode_name[_saveStateCode_index[i]:_saveStateCode_index[i+1]]
}
