language: go

go:
  - "1.11"

before_install:
  # protoc
  - curl -L https://github.com/google/protobuf/releases/download/v3.5.1/protoc-3.5.1-linux-x86_64.zip -o /tmp/protoc.zip
  - unzip /tmp/protoc.zip -d "$HOME"/protoc
  - mkdir -p "$HOME"/src && ln -s "$HOME"/protoc "$HOME"/src/protobuf

  # go deps
  - make deps
  - make generate
  - go get -t -v ./...
  - make lint

env:
  - PATH=$HOME/protoc/bin:$PATH

install:
  - make build

script:
  - ./coverage.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
