language: go

go:
  - "1.12.x"

before_install:
  - sudo chown -R "$USER" /usr/local/
  - make env
  - make generate

env:
  - PATH=$PATH:/usr/local/bin GO111MODULE=on

install:
  - make build

script:
  # - make lint
  - make test
  - make integration_test

after_success:
  - bash <(curl -s https://codecov.io/bash)
