language: go

go:
  - "1.10"

before_install:
  - make deps
  - make build
  - go get -t -v ./...

script:
  - go test -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
