# Web REST API
web:
  listen_endpoint: "localhost:46218"

# GRPC API
api:
  listen_endpoint: "localhost:46219"

# storage
storage:
  filesystem:
    data_dir: "/tmp/memprofiler"
    sync_write: false

# logging
logging:
  level: "debug"
