# Web REST API
web:
  listen_endpoint: "localhost:46218"

# GRPC API
api:
  listen_endpoint: "localhost:46219"

# storage
storage:
  filesystem:
    data_dir: "/tmp/memprofiler"
    sync_write: false

# metrics
metrics:
  # list of averaging intervals
  averaging_windows:
    - 30s   # 30 seconds
    - 5m    # 5 minutes

# logging
logging:
  level: "debug"
