// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package schema

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// InstanceDescription describes a service instance whose memory stats is being tracked
type InstanceDescription struct {
	// type - general service description (kind, role and so on)
	// @inject_tag: yaml:"service_name"
	ServiceName string `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty" yaml:"service_name"`
	// name - unique id of a particular service instance (it may be IP or node ID, and so on)
	// @inject_tag: yaml:"instance_name"
	InstanceName         string   `protobuf:"bytes,2,opt,name=instance_name,json=instanceName,proto3" json:"instance_name,omitempty" yaml:"instance_name"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstanceDescription) Reset()         { *m = InstanceDescription{} }
func (m *InstanceDescription) String() string { return proto.CompactTextString(m) }
func (*InstanceDescription) ProtoMessage()    {}
func (*InstanceDescription) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

func (m *InstanceDescription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstanceDescription.Unmarshal(m, b)
}
func (m *InstanceDescription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstanceDescription.Marshal(b, m, deterministic)
}
func (m *InstanceDescription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstanceDescription.Merge(m, src)
}
func (m *InstanceDescription) XXX_Size() int {
	return xxx_messageInfo_InstanceDescription.Size(m)
}
func (m *InstanceDescription) XXX_DiscardUnknown() {
	xxx_messageInfo_InstanceDescription.DiscardUnknown(m)
}

var xxx_messageInfo_InstanceDescription proto.InternalMessageInfo

func (m *InstanceDescription) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *InstanceDescription) GetInstanceName() string {
	if m != nil {
		return m.InstanceName
	}
	return ""
}

// SessionDescription identifies a single memory tracking session for
// a particular service instance. Typically every service restart
// terminates current session (if there is any) and starts new one.
type SessionDescription struct {
	// instance - service instance identifier
	InstanceDescription *InstanceDescription `protobuf:"bytes,1,opt,name=instance_description,json=instanceDescription,proto3" json:"instance_description,omitempty"`
	// id - unique session identifier
	Id                   int64    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionDescription) Reset()         { *m = SessionDescription{} }
func (m *SessionDescription) String() string { return proto.CompactTextString(m) }
func (*SessionDescription) ProtoMessage()    {}
func (*SessionDescription) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{1}
}

func (m *SessionDescription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionDescription.Unmarshal(m, b)
}
func (m *SessionDescription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionDescription.Marshal(b, m, deterministic)
}
func (m *SessionDescription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionDescription.Merge(m, src)
}
func (m *SessionDescription) XXX_Size() int {
	return xxx_messageInfo_SessionDescription.Size(m)
}
func (m *SessionDescription) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionDescription.DiscardUnknown(m)
}

var xxx_messageInfo_SessionDescription proto.InternalMessageInfo

func (m *SessionDescription) GetInstanceDescription() *InstanceDescription {
	if m != nil {
		return m.InstanceDescription
	}
	return nil
}

func (m *SessionDescription) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// SessionMetadata contains server-side session metadata
type SessionMetadata struct {
	// started_at - time when session has started (UTC)
	StartedAt *timestamp.Timestamp `protobuf:"bytes,1,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	// finished_at - time when session has stopped (UTC), may be empty if session is still alive
	FinishedAt           *timestamp.Timestamp `protobuf:"bytes,2,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SessionMetadata) Reset()         { *m = SessionMetadata{} }
func (m *SessionMetadata) String() string { return proto.CompactTextString(m) }
func (*SessionMetadata) ProtoMessage()    {}
func (*SessionMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{2}
}

func (m *SessionMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionMetadata.Unmarshal(m, b)
}
func (m *SessionMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionMetadata.Marshal(b, m, deterministic)
}
func (m *SessionMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionMetadata.Merge(m, src)
}
func (m *SessionMetadata) XXX_Size() int {
	return xxx_messageInfo_SessionMetadata.Size(m)
}
func (m *SessionMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_SessionMetadata proto.InternalMessageInfo

func (m *SessionMetadata) GetStartedAt() *timestamp.Timestamp {
	if m != nil {
		return m.StartedAt
	}
	return nil
}

func (m *SessionMetadata) GetFinishedAt() *timestamp.Timestamp {
	if m != nil {
		return m.FinishedAt
	}
	return nil
}

// Session combines all available information about a memory tracking session
type Session struct {
	Description          *SessionDescription `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Metadata             *SessionMetadata    `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Session) Reset()         { *m = Session{} }
func (m *Session) String() string { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()    {}
func (*Session) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{3}
}

func (m *Session) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Session.Unmarshal(m, b)
}
func (m *Session) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Session.Marshal(b, m, deterministic)
}
func (m *Session) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Session.Merge(m, src)
}
func (m *Session) XXX_Size() int {
	return xxx_messageInfo_Session.Size(m)
}
func (m *Session) XXX_DiscardUnknown() {
	xxx_messageInfo_Session.DiscardUnknown(m)
}

var xxx_messageInfo_Session proto.InternalMessageInfo

func (m *Session) GetDescription() *SessionDescription {
	if m != nil {
		return m.Description
	}
	return nil
}

func (m *Session) GetMetadata() *SessionMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func init() {
	proto.RegisterType((*InstanceDescription)(nil), "schema.InstanceDescription")
	proto.RegisterType((*SessionDescription)(nil), "schema.SessionDescription")
	proto.RegisterType((*SessionMetadata)(nil), "schema.SessionMetadata")
	proto.RegisterType((*Session)(nil), "schema.Session")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_555bd8c177793206) }

var fileDescriptor_555bd8c177793206 = []byte{
	// 291 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0x3f, 0x4b, 0x33, 0x41,
	0x10, 0xc6, 0xc9, 0xbd, 0x90, 0xd7, 0xcc, 0x9d, 0x0a, 0x1b, 0x41, 0x39, 0x0b, 0xf5, 0x6c, 0xac,
	0x36, 0x60, 0x2a, 0xd1, 0x26, 0x60, 0x63, 0x61, 0x8a, 0xd5, 0x56, 0xc2, 0xe6, 0x6e, 0x92, 0x0c,
	0xb8, 0xbb, 0xc7, 0xed, 0x68, 0xe5, 0x17, 0xf0, 0x5b, 0x8b, 0x77, 0xbb, 0x31, 0x98, 0x80, 0xed,
	0xf0, 0x7b, 0xe6, 0xf9, 0x03, 0x59, 0xe9, 0x8c, 0x71, 0x56, 0xd6, 0x8d, 0x63, 0x27, 0xfa, 0xbe,
	0x5c, 0xa1, 0xd1, 0xf9, 0xd9, 0xd2, 0xb9, 0xe5, 0x2b, 0x8e, 0xda, 0xeb, 0xfc, 0x6d, 0x31, 0x62,
	0x32, 0xe8, 0x59, 0x9b, 0xba, 0x03, 0x8b, 0x17, 0x18, 0x3e, 0x58, 0xcf, 0xda, 0x96, 0x78, 0x8f,
	0xbe, 0x6c, 0xa8, 0x66, 0x72, 0x56, 0x5c, 0x40, 0xe6, 0xb1, 0x79, 0xa7, 0x12, 0x67, 0x56, 0x1b,
	0x3c, 0xe9, 0x9d, 0xf7, 0xae, 0x06, 0x2a, 0x0d, 0xb7, 0xa9, 0x36, 0x28, 0x2e, 0x61, 0x9f, 0x82,
	0xb2, 0x63, 0x92, 0x96, 0xc9, 0xe2, 0xf1, 0x1b, 0x2a, 0x18, 0xc4, 0x13, 0x7a, 0x4f, 0xce, 0x6e,
	0x7e, 0x9f, 0xc2, 0xd1, 0x5a, 0x5a, 0xfd, 0xdc, 0x5b, 0x97, 0xf4, 0xfa, 0x54, 0x76, 0xe1, 0xe5,
	0x8e, 0x60, 0x6a, 0x48, 0x3b, 0xd2, 0x1e, 0x40, 0x42, 0x55, 0xeb, 0xff, 0x4f, 0x25, 0x54, 0x15,
	0x9f, 0x3d, 0x38, 0x0c, 0xb6, 0x8f, 0xc8, 0xba, 0xd2, 0xac, 0xc5, 0x0d, 0x80, 0x67, 0xdd, 0x30,
	0x56, 0x33, 0xcd, 0xc1, 0x29, 0x97, 0xdd, 0x3c, 0x32, 0xce, 0x23, 0x9f, 0xe3, 0x3c, 0x6a, 0x10,
	0xe8, 0x09, 0x8b, 0x5b, 0x48, 0x17, 0x64, 0xc9, 0xaf, 0x3a, 0x6d, 0xf2, 0xa7, 0x16, 0x22, 0x3e,
	0xe1, 0xe2, 0x03, 0xfe, 0x87, 0x28, 0xe2, 0x0e, 0xd2, 0xed, 0xb6, 0x79, 0x6c, 0xbb, 0xbd, 0x93,
	0xda, 0xc4, 0xc5, 0x18, 0xf6, 0x4c, 0x28, 0x13, 0x22, 0x1c, 0xff, 0x92, 0xc6, 0xae, 0x6a, 0x0d,
	0xce, 0xfb, 0x6d, 0xba, 0xf1, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7f, 0x2d, 0xb8, 0xd0, 0x1e,
	0x02, 0x00, 0x00,
}
