// Code generated by protoc-gen-go. DO NOT EDIT.
// source: memprofiler.proto

package schema

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// SaveRequest - request for Save method
type SaveRequest struct {
	// Types that are valid to be assigned to Payload:
	//	*SaveRequest_ServiceDescription
	//	*SaveRequest_Measurement
	Payload              isSaveRequest_Payload `protobuf_oneof:"payload"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *SaveRequest) Reset()         { *m = SaveRequest{} }
func (m *SaveRequest) String() string { return proto.CompactTextString(m) }
func (*SaveRequest) ProtoMessage()    {}
func (*SaveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_078353f0cee2d917, []int{0}
}

func (m *SaveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveRequest.Unmarshal(m, b)
}
func (m *SaveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveRequest.Marshal(b, m, deterministic)
}
func (m *SaveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveRequest.Merge(m, src)
}
func (m *SaveRequest) XXX_Size() int {
	return xxx_messageInfo_SaveRequest.Size(m)
}
func (m *SaveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaveRequest proto.InternalMessageInfo

type isSaveRequest_Payload interface {
	isSaveRequest_Payload()
}

type SaveRequest_ServiceDescription struct {
	ServiceDescription *ServiceDescription `protobuf:"bytes,1,opt,name=service_description,json=serviceDescription,proto3,oneof"`
}

type SaveRequest_Measurement struct {
	Measurement *Measurement `protobuf:"bytes,2,opt,name=measurement,proto3,oneof"`
}

func (*SaveRequest_ServiceDescription) isSaveRequest_Payload() {}

func (*SaveRequest_Measurement) isSaveRequest_Payload() {}

func (m *SaveRequest) GetPayload() isSaveRequest_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *SaveRequest) GetServiceDescription() *ServiceDescription {
	if x, ok := m.GetPayload().(*SaveRequest_ServiceDescription); ok {
		return x.ServiceDescription
	}
	return nil
}

func (m *SaveRequest) GetMeasurement() *Measurement {
	if x, ok := m.GetPayload().(*SaveRequest_Measurement); ok {
		return x.Measurement
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SaveRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SaveRequest_ServiceDescription)(nil),
		(*SaveRequest_Measurement)(nil),
	}
}

// SaveResponse - response for Save method
type SaveResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveResponse) Reset()         { *m = SaveResponse{} }
func (m *SaveResponse) String() string { return proto.CompactTextString(m) }
func (*SaveResponse) ProtoMessage()    {}
func (*SaveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_078353f0cee2d917, []int{1}
}

func (m *SaveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveResponse.Unmarshal(m, b)
}
func (m *SaveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveResponse.Marshal(b, m, deterministic)
}
func (m *SaveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveResponse.Merge(m, src)
}
func (m *SaveResponse) XXX_Size() int {
	return xxx_messageInfo_SaveResponse.Size(m)
}
func (m *SaveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SaveResponse proto.InternalMessageInfo

// ServiceDescription describes the service whose memory stats is being tracked
type ServiceDescription struct {
	// type - general service description
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// instance - description of a particular service instance
	Instance             string   `protobuf:"bytes,2,opt,name=instance,proto3" json:"instance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceDescription) Reset()         { *m = ServiceDescription{} }
func (m *ServiceDescription) String() string { return proto.CompactTextString(m) }
func (*ServiceDescription) ProtoMessage()    {}
func (*ServiceDescription) Descriptor() ([]byte, []int) {
	return fileDescriptor_078353f0cee2d917, []int{2}
}

func (m *ServiceDescription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceDescription.Unmarshal(m, b)
}
func (m *ServiceDescription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceDescription.Marshal(b, m, deterministic)
}
func (m *ServiceDescription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceDescription.Merge(m, src)
}
func (m *ServiceDescription) XXX_Size() int {
	return xxx_messageInfo_ServiceDescription.Size(m)
}
func (m *ServiceDescription) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceDescription.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceDescription proto.InternalMessageInfo

func (m *ServiceDescription) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ServiceDescription) GetInstance() string {
	if m != nil {
		return m.Instance
	}
	return ""
}

// Measurement contains instantaneous memory usage stats
type Measurement struct {
	// observed_at - measurement timestamp
	ObservedAt *timestamp.Timestamp `protobuf:"bytes,1,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	// locations - list of known memory allocations occured in a process
	Locations            []*Location `protobuf:"bytes,2,rep,name=locations,proto3" json:"locations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Measurement) Reset()         { *m = Measurement{} }
func (m *Measurement) String() string { return proto.CompactTextString(m) }
func (*Measurement) ProtoMessage()    {}
func (*Measurement) Descriptor() ([]byte, []int) {
	return fileDescriptor_078353f0cee2d917, []int{3}
}

func (m *Measurement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Measurement.Unmarshal(m, b)
}
func (m *Measurement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Measurement.Marshal(b, m, deterministic)
}
func (m *Measurement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Measurement.Merge(m, src)
}
func (m *Measurement) XXX_Size() int {
	return xxx_messageInfo_Measurement.Size(m)
}
func (m *Measurement) XXX_DiscardUnknown() {
	xxx_messageInfo_Measurement.DiscardUnknown(m)
}

var xxx_messageInfo_Measurement proto.InternalMessageInfo

func (m *Measurement) GetObservedAt() *timestamp.Timestamp {
	if m != nil {
		return m.ObservedAt
	}
	return nil
}

func (m *Measurement) GetLocations() []*Location {
	if m != nil {
		return m.Locations
	}
	return nil
}

// Location contains memory allocation stats with
// information about where memory was actually allocated
type Location struct {
	MemoryUsage          *MemoryUsage `protobuf:"bytes,1,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	Callstack            *Callstack   `protobuf:"bytes,2,opt,name=callstack,proto3" json:"callstack,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_078353f0cee2d917, []int{4}
}

func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (m *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(m, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetMemoryUsage() *MemoryUsage {
	if m != nil {
		return m.MemoryUsage
	}
	return nil
}

func (m *Location) GetCallstack() *Callstack {
	if m != nil {
		return m.Callstack
	}
	return nil
}

// MemoryUsage contains memory usage stats for a particular call stack;
// this stats comes directly from Go runtime
type MemoryUsage struct {
	AllocObjects         int64    `protobuf:"varint,1,opt,name=alloc_objects,json=allocObjects,proto3" json:"alloc_objects,omitempty"`
	AllocBytes           int64    `protobuf:"varint,2,opt,name=alloc_bytes,json=allocBytes,proto3" json:"alloc_bytes,omitempty"`
	FreeObjects          int64    `protobuf:"varint,3,opt,name=free_objects,json=freeObjects,proto3" json:"free_objects,omitempty"`
	FreeBytes            int64    `protobuf:"varint,4,opt,name=free_bytes,json=freeBytes,proto3" json:"free_bytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MemoryUsage) Reset()         { *m = MemoryUsage{} }
func (m *MemoryUsage) String() string { return proto.CompactTextString(m) }
func (*MemoryUsage) ProtoMessage()    {}
func (*MemoryUsage) Descriptor() ([]byte, []int) {
	return fileDescriptor_078353f0cee2d917, []int{5}
}

func (m *MemoryUsage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemoryUsage.Unmarshal(m, b)
}
func (m *MemoryUsage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemoryUsage.Marshal(b, m, deterministic)
}
func (m *MemoryUsage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemoryUsage.Merge(m, src)
}
func (m *MemoryUsage) XXX_Size() int {
	return xxx_messageInfo_MemoryUsage.Size(m)
}
func (m *MemoryUsage) XXX_DiscardUnknown() {
	xxx_messageInfo_MemoryUsage.DiscardUnknown(m)
}

var xxx_messageInfo_MemoryUsage proto.InternalMessageInfo

func (m *MemoryUsage) GetAllocObjects() int64 {
	if m != nil {
		return m.AllocObjects
	}
	return 0
}

func (m *MemoryUsage) GetAllocBytes() int64 {
	if m != nil {
		return m.AllocBytes
	}
	return 0
}

func (m *MemoryUsage) GetFreeObjects() int64 {
	if m != nil {
		return m.FreeObjects
	}
	return 0
}

func (m *MemoryUsage) GetFreeBytes() int64 {
	if m != nil {
		return m.FreeBytes
	}
	return 0
}

// Callstack describes call stack of memory allocation event
type Callstack struct {
	// id represents unique identifier for a particular stack
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// frames describes the place code where heap allocation occured
	Frames               []*StackFrame `protobuf:"bytes,2,rep,name=frames,proto3" json:"frames,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Callstack) Reset()         { *m = Callstack{} }
func (m *Callstack) String() string { return proto.CompactTextString(m) }
func (*Callstack) ProtoMessage()    {}
func (*Callstack) Descriptor() ([]byte, []int) {
	return fileDescriptor_078353f0cee2d917, []int{6}
}

func (m *Callstack) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Callstack.Unmarshal(m, b)
}
func (m *Callstack) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Callstack.Marshal(b, m, deterministic)
}
func (m *Callstack) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Callstack.Merge(m, src)
}
func (m *Callstack) XXX_Size() int {
	return xxx_messageInfo_Callstack.Size(m)
}
func (m *Callstack) XXX_DiscardUnknown() {
	xxx_messageInfo_Callstack.DiscardUnknown(m)
}

var xxx_messageInfo_Callstack proto.InternalMessageInfo

func (m *Callstack) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Callstack) GetFrames() []*StackFrame {
	if m != nil {
		return m.Frames
	}
	return nil
}

// StackFrame provides information about a single stack frame
type StackFrame struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	File                 string   `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	Line                 int32    `protobuf:"varint,3,opt,name=line,proto3" json:"line,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StackFrame) Reset()         { *m = StackFrame{} }
func (m *StackFrame) String() string { return proto.CompactTextString(m) }
func (*StackFrame) ProtoMessage()    {}
func (*StackFrame) Descriptor() ([]byte, []int) {
	return fileDescriptor_078353f0cee2d917, []int{7}
}

func (m *StackFrame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StackFrame.Unmarshal(m, b)
}
func (m *StackFrame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StackFrame.Marshal(b, m, deterministic)
}
func (m *StackFrame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StackFrame.Merge(m, src)
}
func (m *StackFrame) XXX_Size() int {
	return xxx_messageInfo_StackFrame.Size(m)
}
func (m *StackFrame) XXX_DiscardUnknown() {
	xxx_messageInfo_StackFrame.DiscardUnknown(m)
}

var xxx_messageInfo_StackFrame proto.InternalMessageInfo

func (m *StackFrame) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StackFrame) GetFile() string {
	if m != nil {
		return m.File
	}
	return ""
}

func (m *StackFrame) GetLine() int32 {
	if m != nil {
		return m.Line
	}
	return 0
}

func init() {
	proto.RegisterType((*SaveRequest)(nil), "schema.SaveRequest")
	proto.RegisterType((*SaveResponse)(nil), "schema.SaveResponse")
	proto.RegisterType((*ServiceDescription)(nil), "schema.ServiceDescription")
	proto.RegisterType((*Measurement)(nil), "schema.Measurement")
	proto.RegisterType((*Location)(nil), "schema.Location")
	proto.RegisterType((*MemoryUsage)(nil), "schema.MemoryUsage")
	proto.RegisterType((*Callstack)(nil), "schema.Callstack")
	proto.RegisterType((*StackFrame)(nil), "schema.StackFrame")
}

func init() { proto.RegisterFile("memprofiler.proto", fileDescriptor_078353f0cee2d917) }

var fileDescriptor_078353f0cee2d917 = []byte{
	// 496 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x53, 0x41, 0x8f, 0xd3, 0x3c,
	0x10, 0x6d, 0xda, 0x7e, 0xfd, 0x36, 0x93, 0xb2, 0x62, 0x67, 0x39, 0x54, 0x95, 0xd0, 0x2e, 0xe1,
	0x52, 0x71, 0x48, 0xa5, 0x22, 0xe0, 0xc0, 0x89, 0xa5, 0x82, 0x1e, 0x58, 0x21, 0x79, 0xe1, 0x5c,
	0x39, 0xc9, 0xb4, 0x04, 0xe2, 0x38, 0xd8, 0xee, 0x4a, 0xe5, 0x7f, 0x70, 0xe7, 0xa7, 0x22, 0x3b,
	0x71, 0x52, 0xb4, 0x37, 0xe7, 0xcd, 0xcb, 0x9b, 0x99, 0xe7, 0x67, 0xb8, 0x10, 0x24, 0x6a, 0x25,
	0x77, 0x45, 0x49, 0x2a, 0xa9, 0x95, 0x34, 0x12, 0x27, 0x3a, 0xfb, 0x46, 0x82, 0xcf, 0xaf, 0xf6,
	0x52, 0xee, 0x4b, 0x5a, 0x3a, 0x34, 0x3d, 0xec, 0x96, 0xa6, 0x10, 0xa4, 0x0d, 0x17, 0x75, 0x43,
	0x8c, 0xff, 0x04, 0x10, 0xdd, 0xf1, 0x7b, 0x62, 0xf4, 0xf3, 0x40, 0xda, 0xe0, 0x2d, 0x5c, 0x6a,
	0x52, 0xf7, 0x45, 0x46, 0xdb, 0x9c, 0x74, 0xa6, 0x8a, 0xda, 0x14, 0xb2, 0x9a, 0x05, 0xd7, 0xc1,
	0x22, 0x5a, 0xcd, 0x93, 0x46, 0x36, 0xb9, 0x6b, 0x28, 0xeb, 0x9e, 0xb1, 0x19, 0x30, 0xd4, 0x0f,
	0x50, 0x7c, 0x03, 0x91, 0x20, 0xae, 0x0f, 0x8a, 0x04, 0x55, 0x66, 0x36, 0x74, 0x32, 0x97, 0x5e,
	0xe6, 0xb6, 0x2f, 0x6d, 0x06, 0xec, 0x94, 0x79, 0x13, 0xc2, 0xff, 0x35, 0x3f, 0x96, 0x92, 0xe7,
	0xf1, 0x39, 0x4c, 0x9b, 0x09, 0x75, 0x2d, 0x2b, 0x4d, 0xf1, 0x1a, 0xf0, 0x61, 0x7f, 0x44, 0x18,
	0x9b, 0x63, 0x4d, 0x6e, 0xd2, 0x90, 0xb9, 0x33, 0xce, 0xe1, 0xac, 0xa8, 0xb4, 0xe1, 0x55, 0x46,
	0xae, 0x75, 0xc8, 0xba, 0xef, 0xf8, 0x17, 0x44, 0x27, 0xed, 0xf1, 0x2d, 0x44, 0x32, 0xb5, 0x0b,
	0x50, 0xbe, 0xe5, 0xa6, 0xdb, 0xb7, 0xb1, 0x2f, 0xf1, 0xf6, 0x25, 0x5f, 0xbc, 0x7d, 0x0c, 0x3c,
	0xfd, 0x9d, 0xc1, 0x04, 0xc2, 0x52, 0x66, 0xdc, 0xce, 0xa1, 0x67, 0xc3, 0xeb, 0xd1, 0x22, 0x5a,
	0x3d, 0xf6, 0x3b, 0x7e, 0x6a, 0x0b, 0xac, 0xa7, 0xc4, 0x1a, 0xce, 0x3c, 0x8c, 0xaf, 0x61, 0x2a,
	0x48, 0x48, 0x75, 0xdc, 0x1e, 0x34, 0xdf, 0x53, 0xdb, 0xf9, 0xc4, 0x22, 0x5b, 0xfb, 0x6a, 0x4b,
	0xd6, 0xa0, 0xee, 0x03, 0x97, 0x10, 0x66, 0xbc, 0x2c, 0xb5, 0xe1, 0xd9, 0x8f, 0xd6, 0xd7, 0x0b,
	0xff, 0xd3, 0x7b, 0x5f, 0x60, 0x3d, 0x27, 0xfe, 0x1d, 0xd8, 0x8d, 0x7b, 0x81, 0xe7, 0xf0, 0x88,
	0x97, 0xa5, 0xcc, 0xb6, 0x32, 0xfd, 0x4e, 0x99, 0xd1, 0xae, 0xf3, 0x88, 0x4d, 0x1d, 0xf8, 0xb9,
	0xc1, 0xf0, 0x0a, 0xa2, 0x86, 0x94, 0x1e, 0x0d, 0x69, 0xd7, 0x67, 0xc4, 0xc0, 0x41, 0x37, 0x16,
	0xc1, 0x67, 0x30, 0xdd, 0x29, 0xa2, 0x4e, 0x64, 0xe4, 0x18, 0x91, 0xc5, 0xbc, 0xc6, 0x53, 0x00,
	0x47, 0x69, 0x24, 0xc6, 0x8e, 0x10, 0x5a, 0xc4, 0x29, 0xc4, 0x1f, 0x21, 0xec, 0xe6, 0xc5, 0x73,
	0x18, 0x16, 0x79, 0x7b, 0x87, 0xc3, 0x22, 0xc7, 0x17, 0x30, 0xd9, 0x29, 0x2e, 0xc8, 0xdb, 0x8a,
	0x5d, 0x02, 0x2d, 0xfd, 0x83, 0x2d, 0xb1, 0x96, 0x11, 0x6f, 0x00, 0x7a, 0xd4, 0xe6, 0xa1, 0xe2,
	0xa2, 0xcb, 0x43, 0xd5, 0x62, 0xf6, 0x91, 0xb4, 0x59, 0x70, 0x67, 0x8b, 0x95, 0x45, 0x45, 0x6e,
	0xf0, 0xff, 0x98, 0x3b, 0xaf, 0xd6, 0xce, 0x29, 0xff, 0xa4, 0xf0, 0x15, 0x8c, 0x6d, 0x00, 0xb1,
	0xbb, 0x94, 0x93, 0x07, 0x33, 0x7f, 0xf2, 0x2f, 0xd8, 0x66, 0x74, 0xb0, 0x08, 0xd2, 0x89, 0x4b,
	0xcd, 0xcb, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xf1, 0x60, 0xd9, 0x81, 0x9f, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MemprofilerClient is the client API for Memprofiler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MemprofilerClient interface {
	Save(ctx context.Context, opts ...grpc.CallOption) (Memprofiler_SaveClient, error)
}

type memprofilerClient struct {
	cc *grpc.ClientConn
}

func NewMemprofilerClient(cc *grpc.ClientConn) MemprofilerClient {
	return &memprofilerClient{cc}
}

func (c *memprofilerClient) Save(ctx context.Context, opts ...grpc.CallOption) (Memprofiler_SaveClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Memprofiler_serviceDesc.Streams[0], "/schema.Memprofiler/Save", opts...)
	if err != nil {
		return nil, err
	}
	x := &memprofilerSaveClient{stream}
	return x, nil
}

type Memprofiler_SaveClient interface {
	Send(*SaveRequest) error
	CloseAndRecv() (*SaveResponse, error)
	grpc.ClientStream
}

type memprofilerSaveClient struct {
	grpc.ClientStream
}

func (x *memprofilerSaveClient) Send(m *SaveRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *memprofilerSaveClient) CloseAndRecv() (*SaveResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(SaveResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MemprofilerServer is the server API for Memprofiler service.
type MemprofilerServer interface {
	Save(Memprofiler_SaveServer) error
}

func RegisterMemprofilerServer(s *grpc.Server, srv MemprofilerServer) {
	s.RegisterService(&_Memprofiler_serviceDesc, srv)
}

func _Memprofiler_Save_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MemprofilerServer).Save(&memprofilerSaveServer{stream})
}

type Memprofiler_SaveServer interface {
	SendAndClose(*SaveResponse) error
	Recv() (*SaveRequest, error)
	grpc.ServerStream
}

type memprofilerSaveServer struct {
	grpc.ServerStream
}

func (x *memprofilerSaveServer) SendAndClose(m *SaveResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *memprofilerSaveServer) Recv() (*SaveRequest, error) {
	m := new(SaveRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Memprofiler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "schema.Memprofiler",
	HandlerType: (*MemprofilerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Save",
			Handler:       _Memprofiler_Save_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "memprofiler.proto",
}
